### ISSUE TITLE
Compilation error when defining FULL_DMA_BUFFER

### ISSUE THREAD

**Issue by StjnTS** [hpwit/I2SClocklessVirtualLedDriver#10]
Hello, 

When I define 'FULL_DMA_BUFFER' in my code, I get an compilation error pointing to the I2SClocklessVirtualLedDriver.h.

Do you know how I can fix this?

![compilation_error](https://github.com/hpwit/I2SClocklessVirtualLedDriver/assets/154097107/a5e9fa98-8279-4e9c-b6aa-e6df2ae382d2)

**Comment by hpwit** [comment]
Hello
I will have a look at it. 
Can you tell me what you're trying to achieve. Because this option will use a very large amount of memory. 
Rgds
Yves

**Comment by StjnTS** [comment]
Hello Yves,

Thanks for the answer already.

I want to control 32 strips x 130 leds (WS2812B). (4 pins)
I am already using the FASTLEDVIRTUALDRIVER for more than a year on this project. (nice library by the way! :)
I am trying now to improve this project with this I2SClocklessVirtualLedDriver library based on your example FullBufferLoopSync.

Regards,

Stijn

**Comment by hpwit** [comment]
Hello
What are you trying to achieve using the full frame buffer ?
Because this option will use 148k

**Comment by StjnTS** [comment]
I have some trouble with periodic flickering.
Especially when I am setting some leds to black.
I am using interrupts and multithreading, so I hope to fix this flickering with using this frame buffer.
Would you advice this to use the full frame buffer?

**Comment by hpwit** [comment]
Hello
I understand download the dev branch of my repository 
Then add 
#define __NB_DMA_BUFFER 10
Before the #include of the library. 
This should naturally help with your issue. You can increase this number if you still have flickering. 
This new version has a lot of new functionalities that I need to document. 
Let me know

**Comment by StjnTS** [comment]
Hello Yves, 
That worked for me.
I am running it now for serveral hours without flickering.
Thanks!

**Comment by hpwit** [comment]
Great news. 
You're one of the first one to use that branch. 
Can I ask what you're doing with interrupts. I am happy that people are using this library. 
Let me know if you need more help or if you wanna share some
Pictures of your build.

**Comment by StjnTS** [comment]
I am using a timer interrupt to create a fixed base for changing color modes.
It's a christmas tree existing of 32 strips of WS2812B leds controlled by a ESP32.
I've planned to add some extra features next year like streaming and special effects for new year's night.
So I am looking forward to make great use of this library!

![IMG_3941](https://github.com/hpwit/I2SClocklessVirtualLedDriver/assets/154097107/9ac07146-c9bd-43a8-9c5a-d91b5b807cc2)

**Comment by hpwit** [comment]
Great Christmas tree !!!
The new driver has a lot of functionalities to rotate duplicate scale move what you are displaying. For instance https://youtu.be/xJd4ygx5DmQ?si=xd5XUL5WZqUV2kNC

**Comment by StjnTS** [comment]
That looks very nice!
I've seen the video earlier, but I didn't knew it was using this library.
That's something I definitely want to try out.
I will delve into it soon to see which functionalities I can use.
