### ISSUE TITLE
Can I use only 74HC595(s) instead of 74HC245 with 74HC595(s)?

### ISSUE THREAD

**Issue by szf2020** [hpwit/I2SClocklessVirtualLedDriver#17]
Thank you for your excellent library!

Can I use only 74HC595(s) instead of 74HC245 with 74HC595(s)?

Like [https://github.com/Simsso/ShiftRegister74HC595](https://github.com/Simsso/ShiftRegister74HC595)

Is there an example?

**Comment by hpwit** [comment]
Hello,
Here the hc245 so not here to help drive the shift registers, but induces also a slight delay in the clock and latch signal that gives more stability to the output data signal from the shift registers. 
Have you already built the circuit and tried it ?
Rgds
Yves

**Comment by szf2020** [comment]
Thank you for your reply. 
I have made a PCB with 3 cascaded 74HC595.
I will try it. 
I will provide feedback once there are results.

**Comment by hpwit** [comment]
Hello
If you try to use this driver with 3 cascades hc595 it will not work. 
Can you give me more context about what you are trying to achieve ?

**Comment by szf2020** [comment]
[I2SClocklessLedDriver](https://github.com/hpwit/I2SClocklessLedDriver) is more suitable for me, but there are not enough GPIOs on the PCB.

There are  8 * 3 parallel output pins on the PCB.
Each pin can be connected  to 1 pcs WS2812b  led strips. 

Just like using the original FastLed lib.
_`FastLED. addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);`_
