### ISSUE TITLE
Ability to set custom number of pins of every shift register

### ISSUE THREAD

**Issue by particlerain** [hpwit/I2SClocklessVirtualLedDriver#19]
Hi Yves,

I need to use just 5 pins of every shift register, sometimes 4 or 6. Is there a possibility in your driver to set the needed pins of shift registers as a define? For example first 5 outputs of first register will be universe 0-4, skip 3 outputs, then on the next register the first 5 outputs will be universe 5-9 etc. 
Because now when i send 10 universes it uses automatically 8 pins of first register and 2 pins of second register. I would like to organise the shift registers, so that each register outputs 5 universes.

Thanks for any help.

**Comment by hpwit** [comment]
Hello
Normally it's possible the first version of the driver it was 5 pons per shift register. 
I need to see if with all the modifications I have made for it to work with 8pins it's still gonna work by changing the virtual pins number. 
I would certainly have to branch out an old version. 
Can you give me a feedback on the driver (how many pins how many leds) are you happy with it ? Which artnet library are you using?
Regards

**Comment by hpwit** [comment]
This is because you need to change the speed of the i2s bus and at that time i did not program is to be changeable. 
Plus this driver is old and inefficient. The new one also has this parameter but i need some tweaking to make it go the entire driver now.
