### ISSUE TITLE
Arduino dependency

### ISSUE THREAD

**Issue by rbagdazian** [hpwit/I2SClocklessVirtualLedDriver#20]
I noticed that in the file __pixeltypes.h there is a dependency on Arduino.h, but I don't see anything specifically in that file that looks like a reference to the Arduino framework. Is this include strictly necessary in this file? I'm asking because I'd like to use this library in a project that is based on the esp-idf framework instead of the Arduino framework. Thank you for your help!

**Comment by hpwit** [comment]
Hello
Thank you for your interest in my library. 
No you can remove the call to the arduino library. 
Can u know more about your project?
Have you already tried it? If yes how many strips/leds ?  
Sorry if I am asking these questions. It's just that I am interested in it and how the people use this library

**Comment by rbagdazian** [comment]
Great! I found I needed to make a couple of mods when building for esp-idf, but nothing too serious. I'm planning to provide two strips each of which will support up to 300 leds. I'm working on a project that combines a bluetooth speaker with reactive lights in a custom design. I'll clone the repo and make the necessary mods to support esp-idf with the mods being enabled by a #define statement. Once I have it working I'll make a pull request so you can see what mods I made. Thank you!
