### ISSUE TITLE
Extra header in schematic?

### ISSUE THREAD

**Issue by nuttingd** [hpwit/I2SClocklessVirtualLedDriver#25]
Thank you for the amazing work here! This is exactly what I need for a project I'm working on.

I'm fairly new to reading schematics, and I'm getting tripped up as I read the example here: https://github.com/hpwit/I2SClocklessVirtualLedDriver/blob/main/extra/Schematic_4pins-virtual-8-1-20191115225252.png

I can see 3 headers to the left (H1, H2, H3). H2 and H3 look the same and both provide "Clock" and "Latch". There's only one 7HC245 in the diagram, so it seems like one of these headers might be extra (i.e. if there were instead two 7HC245s). Of course more than likely I'm reading this wrong :)

Once again, thank you for this amazing library. 🙏

**Comment by hpwit** [comment]
Hello thank you for your comment !
I had two header incase if you wanted to daisy chain the board. 
How many strips do you need ?
Can you tell me more about your project ?
I have other drawings.

**Comment by nuttingd** [comment]
Ah! That makes sense. I appreciate the help.

I'm building an LED board made of many panels. Pretty much a scaled down version of the LED panel I saw in one of your posts. 

Until now, I have been daisy chaining the panels together, at the cost of very low FPS. I've learned a ton from reading this lib and the various posts that led me to it. I've been able to successfully get a demo working with nothing but a shift register at massive FPS (I ordered some level shifters too, based on what I read about it's affect on signal timing, but haven't needed to use one yet).

Many thanks!

**Comment by nuttingd** [comment]
It's 5 44x11 WS12x strips, btw.

My goal is to use a single data GPIO for simplified wiring. So far it has been working (I'm setting NBIS2SERIALPINS to 1, so not using this lib as intended, but leaning on the timing for the shift register that it provides)
