### ISSUE TITLE
Noise handling

### ISSUE THREAD

**Issue by daonguyen207** [hpwit/I2SClocklessVirtualLedDriver#28]
My led strip sometimes has noise, I checked the control signal and found that with bit0, logic 1 is 0.43us and logic0 is 0.8us. While according to the documentation it is 0.25us and 1us. Is it possible to make the signal more accurate?
![image](https://github.com/user-attachments/assets/5a983cd1-2e99-4db9-b67c-b80f2aacc775)

**Comment by daonguyen207** [comment]
thanks for your library, however after some testing i determined the cause of the noise comes from incorrect bit timing. can you provide a version with 1.25 approach?

**Comment by hpwit** [comment]
I am sorry for that but you are the first one with the timing being an issue.
Can i ask you which leds you are using ? because in the ws2812 i know the timing is not .25 and 1 can you share the data sheet of those ?

**Comment by daonguyen207** [comment]
This is the type of led I use.
I have checked and measured the control signal from the available boards. They are 0.3+0.3 for bit0 and 0.5+0.3 for bit1, strangely 0.25+1 still gives good results, but 0.4+0.8 like the ws2812 strip is noisy.
Can you provide some instructions to be able to customize the DMA buffer for different types of leds?

![image](https://github.com/user-attachments/assets/941a69dd-7d2c-40e3-8728-34f3f3b9f015)

**Comment by hpwit** [comment]
for the virtual driver is not that easy for get close to .25 1 and keep the 8:1 ratio i would need to push the driver at 25.6 Mhz which willnot work on a regular esp32 because above 20mhz it will skip bits. I would have to reduce the number of outputs per 74h595 to 6 instead of 8 so you would be able to control 15*6=90 strips in parallel

**Comment by daonguyen207** [comment]
So are 0.3+0.3 and 0.5+0.3 (or 0.6 + 0.3) achievable?

**Comment by hpwit** [comment]
it's feasible but will require to rewrite part of the driver
