### ISSUE TITLE
Maximum Limit of this driver

### ISSUE THREAD

**Issue by jagspaul** [hpwit/I2SClocklessVirtualLedDriver#7]
Please tell
1. Maximum Pixel capacity
2. Maximum LED STRIP support
3. Maximum NUM_LEDS_PER_STRIP 

supported by this driver.

Thanks & regards

**Comment by hpwit** [comment]
You can put up to 120 strips in parallel 
And the number of led per strip is only limited by the memory. 
Nb: The number of leds per strip will determine the maximum refresh rate
