### ISSUE TITLE
Same concept for in other led driving logic 

### ISSUE THREAD

**Issue by ScobbyDoo** [hpwit/I2SClocklessVirtualLedDriver#9]
https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/issues/533

Please check this out

In this project,leds are not smart like Neopixel , & timing is also not important as Ws2811/12 needed.

What's your idea on this?

**Comment by hpwit** [comment]
Hello
The main issue will be the number of color you'll be able to display. 
The hub75 leds are to be light up physically (the cpu is physically replacing the small IC inside the addressable leds ws2812,apa102....). 
Hence to create for instance different brightness of red I need to light up different leds for different timing. 
The faster you can refresh the leds the more color depth you have and the less flickering. 
What you ask is technically feasible but to ensure a basic speed of light would split at least several pins. But you'll defently loose color depth. 
It's with the try
